name: ninja_material
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+5 # versioning

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0

  package_info_plus: ^8.3.0

  flutter_svg: ^2.2.0

  shared_preferences: ^2.5.3

  google_mobile_ads: ^6.0.0 # ads
  webview_flutter: ^4.13.0
  flutter_localizations:
    sdk: flutter
  #intl: any
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  #flutter_lints: ^6.0.0

flutter:
  fonts:
  - family: The Hand
    fonts:
      - asset: assets/fonts/The Hand Regular.otf

  uses-material-design: true
  generate: true